version: '3.8'

services:
  supervisor:
    build: 
      context: .
      dockerfile: docker/Dockerfile.supervisor
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - browser
      - code
      - filesystem
      - search
    networks:
      - times1000_network

  browser:
    build:
      context: .
      dockerfile: docker/Dockerfile.browser
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - AGENT_TYPE=browser
      - SERVICE_PORT=8001
    ports:
      - "8001:8001"
    networks:
      - times1000_network

  code:
    build:
      context: .
      dockerfile: docker/Dockerfile.code
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - AGENT_TYPE=code
      - SERVICE_PORT=8002
    ports:
      - "8002:8002"
    networks:
      - times1000_network

  filesystem:
    build:
      context: .
      dockerfile: docker/Dockerfile.filesystem
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - AGENT_TYPE=filesystem
      - SERVICE_PORT=8003
    ports:
      - "8003:8003"
    networks:
      - times1000_network

  search:
    build:
      context: .
      dockerfile: docker/Dockerfile.search
    volumes:
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - AGENT_TYPE=search
      - SERVICE_PORT=8004
    ports:
      - "8004:8004"
    networks:
      - times1000_network

networks:
  times1000_network:
    driver: bridge